name: sidescroller
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - comm=0.1.3=pyhd8ed1ab_0
  - debugpy=1.6.7=py311hcafe171_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - ipykernel=6.23.1=pyh210e3f2_0
  - ipython=8.13.2=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py311h38be061_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=3.1.0=hd590300_3
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=pyhd8ed1ab_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.5=py311h2582759_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - python=3.11.3=h2755cc3_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pyzmq=25.0.2=py311hd6ccaeb_0
  - readline=8.2=h8228510_1
  - setuptools=67.7.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.3.2=py311h459d7ec_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.6.0=hd8ed1ab_0
  - typing_extensions=4.6.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - pip:
      - accelerate==0.20.0.dev0
      - antlr4-python3-runtime==4.9.3
      - bidict==0.22.1
      - blinker==1.6.2
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.3
      - controlnet-aux==0.0.4
      - diffusers==0.17.0.dev0
      - einops==0.6.1
      - filelock==3.12.0
      - flask==2.3.2
      - flask-cors==3.0.10
      - flask-socketio==5.3.4
      - fsspec==2023.5.0
      - h11==0.14.0
      - huggingface-hub==0.14.1
      - idna==3.4
      - imageio==2.29.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - lazy-loader==0.2
      - lit==16.0.5
      - markupsafe==2.1.2
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - networkx==3.1
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - opencv-contrib-python==4.7.0.72
      - opencv-python==4.7.0.72
      - pillow==9.5.0
      - pyre-extensions==0.0.23
      - python-engineio==4.4.1
      - python-socketio==5.8.0
      - pywavelets==1.4.1
      - pyyaml==6.0
      - regex==2023.5.5
      - requests==2.31.0
      - safetensors==0.3.1
      - scikit-image==0.20.0
      - scipy==1.10.1
      - simple-websocket==0.10.0
      - sympy==1.12
      - tifffile==2023.4.12
      - timm==0.9.2
      - tokenizers==0.13.3
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - transformers==4.29.2
      - triton==2.0.0
      - typing-inspect==0.8.0
      - urllib3==2.0.2
      - werkzeug==2.3.4
      - wsproto==1.2.0
      - xformers==0.0.16
prefix: /home/holson/miniconda3/envs/sidescroller
